version: 2
jobs:
  build:
    working_directory: ~/tmp
    machine:
      node:
        version: 8.9.1
    dependencies:
      override:
        - nvm install 8 && npm install
    test:
      override:
        - nvm use 8 && npm run test-server-all
        - nvm use 8 && npm run ci
    steps:
      - checkout
      - run: npm install
      - run: npm test -- --coverage
      - run: $(npm bin)/cypress run --record
